assignments/urls.py
from django.urls import path, include
import assignments.views

app_name = "assignments"

urlpatterns = [
    path('<slug:course_slug>/newassignment/', assignments.views.assignment_create_view, name='create_assignment'),
    path('<slug:slug>/', assignments.views.assignment_detail_view, name='view_assignment'),
    path('<slug:slug>/deleteassignment/', assignments.views.assignment_delete_view, name='delete_assignment'),
    path('<slug:slug>/publishassignment/', assignments.views.assignment_publish_view, name='publish_assignment'),
    path('<slug:slug>/close_assignment/', assignments.views.assignment_close_view, name='close_assignment'),
    path('<slug:slug>/grade_assignment/', assignments.views.assignment_grade_view, name='grade_assignment'),
    path('<slug:assignment_slug>/comments/<int:index>', assignments.views.student_graded_question_view, name='student_graded_question_view'),
    path('<slug:assignment_slug>/grades', assignments.views.assignment_view_grades_view, name='assignment_view_grades_view'),
    path('<slug:assignment_slug>/grades/download', assignments.views.get_grades_as_csv, name='get_grades_as_csv'),
    path('<slug:slug>/edit_assignment/', assignments.views.assignment_edit_view, name='edit_assignment'),
    path('<slug:assignment_slug>/newquestion/', assignments.views.question_create_view, name='create_question'),
    path('<slug:assignment_slug>/editquestion/<int:index>', assignments.views.question_edit_view, name='edit_question'),
    path('<slug:assignment_slug>/deletequestion/<int:index>', assignments.views.question_delete_view,
         name='delete_question'),
    path('<slug:assignment_slug>/submission/<int:index>', assignments.views.question_submission_edit_view, name='edit_submission'),
    path('<slug:assignment_slug>/submission/submit', assignments.views.submit_submission_view, name='submit_submission'),
    path('<slug:assignment_slug>/review/<int:index>', assignments.views.edit_graded_assignment_submission_view, name='edit_graded_assignment_submission_view'),
    path('<slug:assignment_slug>/review/<int:index>/<int:q_index>', assignments.views.edit_graded_question_submission_view, name='edit_graded_question_submission_view'),
    path('<slug:assignment_slug>/review/<int:index>/submit', assignments.views.submit_graded_assignment_view, name='submit_graded_assignment_view'),
    path('<slug:assignment_slug>/<str:username>', assignments.views.instructor_submission_view, name='instructor_submission_view'),
]

peerGrader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

import users.views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', users.views.home_view, name='home'),
    path('users/', include(('users.urls', 'users'))),
    path('users/', include('django.contrib.auth.urls')),
    # path('courses/<slug:slug>/assignments', include(('assignments.urls', 'assignments'))),
    path('courses/', include(('courses.urls', 'courses'))),
    path('assignments/', include(('assignments.urls', 'assignments'))),
]

users/urls.py
from django.urls import path
from .views import SignUpView, EditUsername

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('newusername/', EditUsername.as_view(), name='change_username'),
]

assignments/views.py
import csv
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect

from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView
import pytz
from datetime import datetime, timedelta

from assignments.models import Assignment, Question, AssignmentSubmission, QuestionSubmission, \
    GradedAssignmentSubmission, GradedQuestionSubmission
from courses.models import Course
from users.models import AppUser

import courses.graphs as graphs
import numpy as np

utc = pytz.UTC


class AssignmentView(DetailView):
    model = Assignment
    slug_url_kwarg = 'slug'
    slug_field = 'slug'

    def get_template_names(self):
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        if self.request.user.is_instructor:
            return 'assignments/instructor_assignment_view.html'
        else:
            if assignment.state == "closed":
                return 'assignments/closed/student_assignment_view.html'
            elif assignment.state == "graded":
                return 'assignments/graded/student_graded_assignment_view.html'
            return 'assignments/student_assignment_view.html'

    # if student, pass assignment submission to context so they can preview their answers
    def get_context_data(self, **kwargs):
        context = super(AssignmentView, self).get_context_data(**kwargs)
        user = self.request.user
        if not user.is_instructor:
            assignment = Assignment.objects.get(slug=self.kwargs['slug'])
            assignment_submission = AssignmentSubmission.objects.get(student=user, assignment=assignment)
            context.update({"assignment_submission": assignment_submission})
            if assignment.state == "closed":
                graded_assignment_submissions = GradedAssignmentSubmission.objects.filter(grader=user,
                                                                                          assignment=assignment)
                context.update({"graded_assignment_submissions": graded_assignment_submissions})
            if assignment.state == "graded":
                graded_assignment_submissions = GradedAssignmentSubmission.objects.filter(
                    assignment_submission=assignment_submission)
                context.update({"graded_assignment_submissions": graded_assignment_submissions})
        return context

    def dispatch(self, request, *args, **kwargs):
        # validate user
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        course = assignment.course
        user = request.user
        if (course.instructor == user) or (user in course.students.all() and assignment.state != "unpublished"):
            return super(AssignmentView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('/')


class CreateAssignment(CreateView):
    model = Assignment
    template_name = 'assignments/createassignment.html'
    fields = ('name', 'due_date',)

    def form_valid(self, form):
        form.instance.course = Course.objects.get(slug=self.kwargs['course_slug'])
        return super(CreateAssignment, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateAssignment, self).get_context_data(**kwargs)
        course = Course.objects.get(slug=self.kwargs['course_slug'])
        context.update({"course": course})
        return context

    def dispatch(self, request, *args, **kwargs):
        # validate user
        course = Course.objects.get(slug=self.kwargs['course_slug'])
        user = request.user
        if not (course.instructor == user):
            return redirect('/')
        else:
            return super(CreateAssignment, self).dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('courses:view_course', kwargs={'slug': self.kwargs['course_slug']})


class DeleteAssignment(DeleteView):
    model = Assignment
    slug_url_kwarg = 'slug'
    slug_field = 'slug'
    success_url = "/"
    template_name = 'assignments/deleteassignment.html'

    def dispatch(self, request, *args, **kwargs):
        # validate user
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        course = assignment.course
        user = request.user
        if not (course.instructor == user):
            return redirect('/')
        else:
            return super(DeleteAssignment, self).dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        return reverse_lazy('courses:view_course', kwargs={'slug': assignment.course.slug})


class EditAssignment(UpdateView):
    model = Assignment
    slug_url_kwarg = 'slug'  # use slug to get specific assignment
    slug_field = 'slug'
    template_name = 'assignments/editassignment.html'
    fields = ('name', 'due_date',)  # specifying what variables in the model need to be modified

    def get_success_url(self, **kwargs):
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        return reverse_lazy('courses:view_course', kwargs={'slug': assignment.course.slug})


class PublishAssignment(UpdateView):
    model = Assignment
    template_name = 'assignments/publish_assignment.html'
    fields = ()
    slug_url_kwarg = 'slug'
    slug_field = 'slug'

    def form_valid(self, form):
        if not form.instance.state == 'published':
            if form.instance.can_publish():
                form.instance.to_state_published()
        else:
            form.instance.to_state_unpublished()
        return super(PublishAssignment, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        # validate user
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        course = assignment.course
        user = request.user
        if not (course.instructor == user):
            return redirect('/')
        else:
            return super(PublishAssignment, self).dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        return reverse_lazy('courses:view_course', kwargs={'slug': assignment.course.slug})


class CloseAssignment(UpdateView):
    model = Assignment
    template_name = 'assignments/close_assignment.html'
    fields = ()
    slug_url_kwarg = 'slug'
    slug_field = 'slug'

    def form_valid(self, form):
        if form.instance.can_close():
            form.instance.to_state_closed()
        return super(CloseAssignment, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        # validate user
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        course = assignment.course
        user = request.user
        if not (course.instructor == user):
            return redirect('/')
        else:
            return super(CloseAssignment, self).dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        return reverse_lazy('courses:view_course', kwargs={'slug': assignment.course.slug})


class GradeAssignment(UpdateView):
    model = Assignment
    template_name = 'assignments/grade_assignment.html'
    fields = ()
    slug_url_kwarg = 'slug'
    slug_field = 'slug'

    def form_valid(self, form):
        if form.instance.can_graded():
            form.instance.to_state_graded()
        return super(GradeAssignment, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        # validate user
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        course = assignment.course
        user = request.user
        if not (course.instructor == user):
            return redirect('/')
        else:
            return super(GradeAssignment, self).dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        assignment = Assignment.objects.get(slug=self.kwargs['slug'])
        return reverse_lazy('courses:view_course', kwargs={'slug': assignment.course.slug})


class CreateQuestion(CreateView):
    model = Question
    template_name = 'questions/createquestion.html'
    fields = ('question_body', 'point_value',)
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.assignment = Assignment.objects.get(slug=self.kwargs['assignment_slug'])
        form.instance.index = Assignment.objects.get(slug=self.kwargs['assignment_slug']).numQuestions() + 1
        return super(CreateQuestion, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        # validate user
        assignment = Assignment.objects.get(slug=self.kwargs['assignment_slug'])
        course = assignment.course
        user = request.user
        if not (course.instructor == user):
            return redirect('/')
        else:
            return super(CreateQuestion, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateQuestion, self).get_context_data(**kwargs)
        assignment = Assignment.objects.get(slug=self.kwargs['assignment_slug'])
        context.update({"assignment": assignment})
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('assignments:view_assignment', kwargs={'slug': self.kwargs['assignment_slug']})


class EditQuestion(UpdateView):
    model = Question
    template_name = 'questions/editquestion.html'
    fields = ('question_body', 'point_value',)
    slug_url_kwarg = 'index'
    slug_field = 'index'
    success_url = "/"

    def get_queryset(self):
        assignment = Assignment.objects.get(slug=self.kwargs['assignment_slug'])
        return Question.objects.filter(assignment=assignment, index=self.kwargs['index'])

assignments/templates/review/edit_graded_assignment_view.html
{% extends "base.html" %}
{% block content %}
    <div>
        <div class="d-flex justify-content-between align-items-center">
            <h1>Assignment: {{ assignment.name }}</h1>
            <a class="btn btn-primary" href="{% url 'assignments:view_assignment' assignment.slug %}">← Back</a>
        </div>
        <hr>
        <div class="d-flex justify-content-between align-items-center">
            <div>
{#                <p>Due: {{ assignment.due_date }}</p>#}
                {% if graded_assignment_submission.is_submitted %}
                    <p>Last submitted at: {{ graded_assignment_submission.submitted_at }}</p>
                {% else %}
                    <p>Not yet submitted</p>
                {% endif %}
            </div>
            <a href="{% url 'assignments:submit_graded_assignment_view' assignment.slug graded_assignment_submission.index %}"
               class="btn btn-outline-primary">Submit</a>
        </div>
    </div>
    {% if graded_question_submissions.all %}
        {% for graded_question_submission in graded_question_submissions.all %}
            <div class="card mt-3 p-3">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h2 class="d-inline">{{ graded_question_submission.question_submission.question.index }}. {{ graded_question_submission.question_submission.question.question_body }}
                            ({% if graded_question_submission.points %}{{ graded_question_submission.points}}/{% endif %}{{ graded_question_submission.question_submission.question.point_value }}
                            point{{ graded_question_submission.question_submission.question.point_value|pluralize }})</h2>
                    </div>
                    <div>
                        <a href="{% url 'assignments:edit_graded_question_submission_view' assignment.slug graded_assignment_submission.index graded_question_submission.question_submission.question.index %}"
                           class="btn btn-outline-primary">Grade</a>
                    </div>
                </div>
                <hr>
                <div>
                    <p>{{ graded_question_submission.question_submission.answer_body }}</p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

assignments/templates/review/edit_graded_question_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Review</h2>
    <h2 class="d-inline">{{ question_submission.question.index }}. {{ question_submission.question.question_body }} ({{ question_submission.question.point_value }} point{{ question_submission.question.point_value|pluralize }})</h2>
    <div class="card mt-3 mb-3 p-3">Answer: {{ question_submission.answer_body }}</div>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3">Save</button>
{#        <a class="btn btn-outline-secondary mt-3" href="{%  url '/' object.question.assignment.slug %}">Cancel</a>#}
    </form>
{% endblock %}

assignments/templates/review/submit_review_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Submit Peer Review</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mt-3">Submit</button>
        <a class="btn btn-outline-secondary mt-3" href="{%  url 'assignments:view_assignment' object.assignment.slug %}">Cancel</a>
    </form>
{% endblock %}