assignments/urls.py
from django.urls import path, include
import assignments.views

app_name = "assignments"

urlpatterns = [
    path('<slug:course_slug>/newassignment/', assignments.views.assignment_create_view, name='create_assignment'),
    path('<slug:slug>/', assignments.views.assignment_detail_view, name='view_assignment'),
    path('<slug:slug>/deleteassignment/', assignments.views.assignment_delete_view, name='delete_assignment'),
    path('<slug:slug>/publishassignment/', assignments.views.assignment_publish_view, name='publish_assignment'),
    path('<slug:slug>/close_assignment/', assignments.views.assignment_close_view, name='close_assignment'),
    path('<slug:slug>/grade_assignment/', assignments.views.assignment_grade_view, name='grade_assignment'),
    path('<slug:assignment_slug>/comments/<int:index>', assignments.views.student_graded_question_view, name='student_graded_question_view'),
    path('<slug:assignment_slug>/grades', assignments.views.assignment_view_grades_view, name='assignment_view_grades_view'),
    path('<slug:assignment_slug>/grades/download', assignments.views.get_grades_as_csv, name='get_grades_as_csv'),
    path('<slug:slug>/edit_assignment/', assignments.views.assignment_edit_view, name='edit_assignment'),
    path('<slug:assignment_slug>/newquestion/', assignments.views.question_create_view, name='create_question'),
    path('<slug:assignment_slug>/editquestion/<int:index>', assignments.views.question_edit_view, name='edit_question'),
    path('<slug:assignment_slug>/deletequestion/<int:index>', assignments.views.question_delete_view,
         name='delete_question'),
    path('<slug:assignment_slug>/submission/<int:index>', assignments.views.question_submission_edit_view, name='edit_submission'),
    path('<slug:assignment_slug>/submission/submit', assignments.views.submit_submission_view, name='submit_submission'),
    path('<slug:assignment_slug>/review/<int:index>', assignments.views.edit_graded_assignment_submission_view, name='edit_graded_assignment_submission_view'),
    path('<slug:assignment_slug>/review/<int:index>/<int:q_index>', assignments.views.edit_graded_question_submission_view, name='edit_graded_question_submission_view'),
    path('<slug:assignment_slug>/review/<int:index>/submit', assignments.views.submit_graded_assignment_view, name='submit_graded_assignment_view'),
    path('<slug:assignment_slug>/<str:username>', assignments.views.instructor_submission_view, name='instructor_submission_view'),
]

courses/urls.py
from django.urls import path, include

import assignments.views
import courses.views

urlpatterns = [
    path('<slug:slug>/', courses.views.course_detail_view, name='view_course'),
    # path('<slug:slug>/assignments/', include('assignments.urls', namespace='assignments')),
]

peerGrader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

import users.views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', users.views.home_view, name='home'),
    path('users/', include(('users.urls', 'users'))),
    path('users/', include('django.contrib.auth.urls')),
    # path('courses/<slug:slug>/assignments', include(('assignments.urls', 'assignments'))),
    path('courses/', include(('courses.urls', 'courses'))),
    path('assignments/', include(('assignments.urls', 'assignments'))),
]

users/urls.py
from django.urls import path
from .views import SignUpView, EditUsername

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('newusername/', EditUsername.as_view(), name='change_username'),
]

courses/models.py
from django.db import models
from autoslug import AutoSlugField

import peerGrader.settings


class Course(models.Model):
    name = models.CharField(max_length=30)
    instructor = models.ForeignKey(peerGrader.settings.AUTH_USER_MODEL,
                                   on_delete=models.CASCADE,
                                   limit_choices_to={'is_instructor': True},
                                   related_name='taught_class')
    students = models.ManyToManyField(peerGrader.settings.AUTH_USER_MODEL,
                                      limit_choices_to={'is_instructor': False},
                                      related_name='enrolled_class')
    slug = AutoSlugField(populate_from='name', unique=True, editable=False)

    def __str__(self):
        return self.name

courses/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from . import graphs
import numpy as np

from courses.models import Course


@login_required()
def course_view(request, slug):
    course = Course.objects.get(slug=slug)
    user = request.user

    # Make sure authenticated user is part of the course
    if not (course.instructor == user or (user in course.students.all())):
        return redirect('/')
    # dont show unpublished assignments to students
    if user.is_instructor:
        assignment_list = course.assignments.all().order_by('slug')
    else:
        assignment_list = course.assignments.filter(~Q(state="unpublished")).order_by('slug')

    page = request.GET.get('page', 1)
    paginator = Paginator(assignment_list, 5)
    try:
        assignments = paginator.page(page)
    except PageNotAnInteger:
        assignments = paginator.page(1)
    except EmptyPage:
        assignments = paginator.page(paginator.num_pages)


    #generate grade distribution graphs and grade stats
    graph_dict = {}
    if user.is_instructor:
        assignment_list = course.assignments.all().order_by('slug')
        # graded_assignments = course.assignments.filter(state="graded")
        for a in course.assignments.filter(state="graded").order_by('slug'):
            scores = []
            for submission in a.assignment_submissions.filter(is_submitted=True):
                scores.append(submission.getScore())
            # graph = graphs.generateGradeChart(scores, a.pointTotal())
            graph_dict[a.slug] = (graphs.generateGradeChart(scores, a.pointTotal()), np.mean(scores), np.median(scores))

    if request.user.is_instructor:
        return render(request, 'courses/instructorcourseview.html', {'course': course, 'assignments': assignments, 'graph_dict' : graph_dict, })
    else:
        return render(request, 'courses/studentcourseview.html', {'course': course, 'assignments': assignments, })


course_detail_view = login_required(course_view)

courses/templates/courses/courseview.html
{% extends "base.html" %}
{% block content %}
    <div>
        <div class="d-flex justify-content-between align-items-center">
            <h1 class="d-inline">Course: {{ course.name }}</h1>
            <a class="btn btn-primary" href="{% url 'home' %}">← Back</a>
        </div>
        <div class="d-flex justify-content-between align-items-center">
            <h3>Instructor: {{ course.instructor.username }}</h3>
            {%  if request.user.is_instructor %}
                <a class="btn btn-outline-primary" href="{% url 'assignments:create_assignment' course.slug %}">Create Assignment</a>
            {% endif %}
        </div>
    </div>
    {% if assignments %}
        {% for Assignment in assignments %}
            <div class="card mt-3 p-3">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h2 class="d-inline">{{ Assignment.name }}</h2>
                    </div>
                    <div>
                        {% if user.is_authenticated and user.is_instructor %}
                            <a href="{% url 'assignments:delete_assignment' Assignment.slug %}" class="btn btn-danger">Delete</a>
                            <a href="{% url 'assignments:edit_assignment' Assignment.slug %}" class="btn btn-outline-primary">Edit Assignment</a>
                        {% endif %}
                        <a href="{% url 'assignments:view_assignment' Assignment.slug %}" class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>
        {% endfor %}

        {% if assignments.has_other_pages %}
            <ul class="mt-3 pagination justify-content-center">
                {% if assignments.has_previous %}
                    <li><a class="page-link" href="?page={{ assignments.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#">&laquo;</a></li>
                {% endif %}
                {% for i in assignments.paginator.page_range %}
                    {% if users.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if assignments.has_next %}
                    <li><a class="page-link" href="?page={{ assignments.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#">&raquo;</a></li>
                {% endif %}
            </ul>
        {% endif %}

    {% else %}
        <h3>There are no assignments.</h3>
    {% endif %}
{% endblock content %}

courses/templates/courses/instructorcourseview.html
{% extends "base.html" %}
{% block content %}
    <div>
        <div class="d-flex justify-content-between align-items-center">
            <h1 class="d-inline">Course: {{ course.name }}</h1>
            <a class="btn btn-primary" href="{% url 'home' %}">← Back</a>
        </div>
        <div class="d-flex justify-content-between align-items-center">
            <h3>Instructor: {{ course.instructor.username }}</h3>
            <a class="btn btn-outline-primary" href="{% url 'assignments:create_assignment' course.slug %}">Create
                Assignment</a>
        </div>
    </div>
    {% if assignments %}
        {% for Assignment in assignments %}

            <!-- Comments Modal -->
            <div class="modal fade" id="submissionsModal-{{ Assignment.slug }}"
                 tabindex="-1" role="dialog"
                 aria-labelledby="commentsModalTitle" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="commentsModalLongTitle">Submission status for
                                {{ Assignment.name }}</h5>
                        </div>
                        <div class="modal-body">


                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Student</th>
                                    <th scope="col">Submitted?</th>
                                    <th scope="col">Link</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for assignment_submission in Assignment.assignment_submissions.all %}
                                    <tr>
                                        <td>{{ assignment_submission.student.username }}</td>
                                        <td>{{ assignment_submission.is_submitted|yesno:"✔,❌" }}</td>
                                        <td>
                                            <a href="{% url 'assignments:instructor_submission_view' Assignment.slug assignment_submission.student.username %}">View
                                                Submission</a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mt-3 p-3">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h2 class="d-inline">{{ Assignment.name }}</h2>
                    </div>
                    <div>
                        {% if Assignment.state == "published" %}
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-outline-primary" data-toggle="modal"
                                    data-target="#submissionsModal-{{ Assignment.slug }}">
                                View Submissions
                            </button>
                            <a href="{% url 'assignments:publish_assignment' Assignment.slug %}"
                               class="btn btn-warning">Unpublish Assignment</a>
                            <a href="{% url 'assignments:close_assignment' Assignment.slug %}"
                               class="btn btn-outline-primary">Close Assignment Submissions</a>
                        {% elif Assignment.state == "unpublished" %}
                            <a href="{% url 'assignments:publish_assignment' Assignment.slug %}"
                               class="btn btn-outline-success">Publish</a>
                            <a href="{% url 'assignments:edit_assignment' Assignment.slug %}"
                               class="btn btn-outline-primary">Edit</a>
                            <a href="{% url 'assignments:delete_assignment' Assignment.slug %}" class="btn btn-danger">Delete</a>
                        {% elif Assignment.state == "closed" %}
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-outline-primary" data-toggle="modal"
                                    data-target="#submissionsModal-{{ Assignment.slug }}">
                                View Submissions
                            </button>
                            <a href="{% url 'assignments:delete_assignment' Assignment.slug %}" class="btn btn-danger">Delete</a>
                            <a href="{% url 'assignments:grade_assignment' Assignment.slug %}"
                               class="btn btn-outline-primary">Grade Assignment</a>
                        {% elif Assignment.state == "graded" %}
                            <button type="button" class="btn btn-outline-primary" data-toggle="modal"
                                    data-target="#submissionsModal-{{ Assignment.slug }}">
                                View Submissions
                            </button>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                    data-target="#gradeModal-{{ Assignment.slug }}">
                                View Grades
                            </button>

                            <!-- Grade Modal -->
                            <div class="modal fade" id="gradeModal-{{ Assignment.slug }}" tabindex="-1" role="dialog"
                                 aria-labelledby="gradeModalTitle" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="gradeModalLongTitle">Grades for
                                                assignment: {{ Assignment.name }}</h5>
                                        </div>
                                        <div class="modal-body">
                                            <table class="table table-striped table-hover">
                                                <thead>
                                                <tr>
                                                    <th scope="col">Student</th>
                                                    <th scope="col">Grade</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for assignment_submission in Assignment.assignment_submissions.all %}
                                                    <tr>
                                                        <td>{{ assignment_submission.student.username }}</td>
                                                        {% if assignment_submission.is_submitted %}
                                                            <td>{{ assignment_submission.getScore }}</td>
                                                        {% else %}
                                                            <td>N/A</td>
                                                        {% endif %}
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                            <div class="d-flex flex-column align-items-center">
                                                <h4>Grade Distribution</h4>
                                            </div>
                                            {% for k,v in graph_dict.items %}
                                                {% if k == Assignment.slug %}
                                                    <div>
                                                        <img class="img-fluid" src="data:image/png;base64,{{ v.0|safe }}">
                                                    </div>
                                                    <div class="d-flex justify-content-around align-items-center mb-3">
                                                        <h5>Mean: {{ v.1 }}</h5>
                                                        <h5>Median: {{ v.2 }}</h5>
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                            </button>
                                            <a type="button" class="btn btn-primary"
                                               href="{% url 'assignments:get_grades_as_csv' Assignment.slug %}">Download
                                                as CSV</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                        <a href="{% url 'assignments:view_assignment' Assignment.slug %}"
                           class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>
        {% endfor %}

        {% if assignments.has_other_pages %}
            <ul class="mt-3 pagination justify-content-center">
                {% if assignments.has_previous %}
                    <li><a class="page-link" href="?page={{ assignments.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#">&laquo;</a></li>
                {% endif %}
                {% for i in assignments.paginator.page_range %}
                    {% if users.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if assignments.has_next %}
                    <li><a class="page-link" href="?page={{ assignments.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#">&raquo;</a></li>
                {% endif %}
            </ul>
        {% endif %}

    {% else %}
        <h5 class="mt-5">There are no assignments. Would you like to <a
                href="{% url 'assignments:create_assignment' course.slug %}">create one?</a></h5>
    {% endif %}

    <script type="text/javascript" src="http://kozea.github.com/pygal.js/latest/pygal-tooltips.min.js"></script>
{% endblock content %}

courses/templates/courses/studentcourseview.html
{% extends "base.html" %}
{% block content %}
    <div>
        <div class="d-flex justify-content-between align-items-center">
            <h1 class="d-inline">Enrolled Course: {{ course.name }}</h1>
            <a class="btn btn-primary" href="{% url 'home' %}">← Back</a>
        </div>
        <div class="d-flex justify-content-between align-items-center">
            <h3>Instructor: {{ course.instructor.username }}</h3>
        </div>
    </div>
    {% if assignments %}
        {% for Assignment in assignments %}
            <div class="card mt-3 p-3">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h2 class="d-inline">{{ Assignment.name }}</h2>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="mx-3">Status: {{ Assignment.state }}</h5>
                        <a href="{% url 'assignments:view_assignment' Assignment.slug %}"
                           class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>
        {% endfor %}

        {% if assignments.has_other_pages %}
            <ul class="mt-3 pagination justify-content-center">
                {% if assignments.has_previous %}
                    <li><a class="page-link" href="?page={{ assignments.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#">&laquo;</a></li>
                {% endif %}
                {% for i in assignments.paginator.page_range %}
                    {% if users.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if assignments.has_next %}
                    <li><a class="page-link" href="?page={{ assignments.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#">&raquo;</a></li>
                {% endif %}
            </ul>
        {% endif %}

    {% else %}
        <h3>There are no assignments.</h3>
    {% endif %}
{% endblock content %}